name: "Hello World"
description: "Greet someone and record the time"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
  collection_path: # id of input
    description: "Relative path to your collection eg ./collection"
    required: true
    default: "./collection"
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node20"
  main: "dist/index.js"
