# name: Test

# on:
#   pull_request:
#     types: [opened]

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: ./

#       - name: Get changed files
#         id: changed-files
#         uses: tj-actions/changed-files@v14.6

#       - name: List all changed files
#         run: |
#           for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
#             echo "$file was changed"
#           done

name: Test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          json: true
          write_output_files: true

      - name: Verify the contents of the .collections/added_files.json file
        # TODO create the file if it doesnt exist
        run: |
          cat ./collections/added_files.json

      # - name: Save changed files to JSON
      #   run: |
      #     echo '${{ toJson(steps.changed-files.outputs.all_changed_files) }}' > changed_files.json

      - name: Upload changed files JSON
        uses: actions/upload-artifact@v4
        with:
          name: changed-files
          path: changed_files.json
          retention-days: 1 # Keep artifact for 1 day

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
